### ISSUE TITLE
mac os 提示找不到微信开发者工具

### ISSUE THREAD

**Issue by NewFuture** [NewFuture/miniprogram-build#48]
![image](https://user-images.githubusercontent.com/28286561/65814248-d0634980-e211-11e9-9073-5b3a5d1976fb.png)
这边还有个问题，我这边装了 "miniprogram-build": "^6.8.0" 以后 我这边是正常的 推到同事电脑以后 npm run start 提示找不到开发者工具 我们尝试了重装开发者工具、重装依赖，都没有效果。。
npm run start 用的是这个："start": "mp --config env/dev.jsonc",

_Originally posted by @Hansuku in https://github.com/NewFuture/miniprogram-build/issues/47#issuecomment-536168308_

**Comment by NewFuture** [comment]
@Hansuku 
这个地方是查找 MacOS下的安装路径
https://github.com/NewFuture/wechat-devtool/blob/ba30215d9b334a35819385a54290c358f807befd/src/lib/cli.ts#L29-L37

1. 在mac上运行一下这个命令的输出
`defaults read com.tencent.wechat.devtools LastRunAppBundlePath`

2. 和这个文件是否存在
`/Applications/wechatwebdevtools.app/Contents/Resources/app.nw/bin/cli`

可能开发工具在mac上的路径改了

**Comment by Hansuku** [comment]
> @Hansuku
> 这个地方是查找 MacOS下的安装路径
> https://github.com/NewFuture/wechat-devtool/blob/ba30215d9b334a35819385a54290c358f807befd/src/lib/cli.ts#L29-L37
> 
> 1. 在mac上运行一下这个命令的输出
>    `defaults read com.tencent.wechat.devtools LastRunAppBundlePath`
> 2. 和这个文件是否存在
>    `/Applications/wechatwebdevtools.app/Contents/Resources/app.nw/bin/cli`
> 
> 可能开发工具在mac上的路径改了

/Applications/wechatwebdevtools.app/Contents/Resources/app.nw/bin/cli 正常存在
defaults read com.tencent.wechat.devtools LastRunAppBundlePath 这个没有正常输出
![image](https://user-images.githubusercontent.com/28286561/65824572-f6cec680-e29d-11e9-8524-5a0b912b9ca7.png)
这个会跟 zsh 环境有关系吗？

**Comment by NewFuture** [comment]
和zsh应该关系不大

这个命令可以调起微信开发者工具么？
```bash
npx wechat-devtool
```

**Comment by Hansuku** [comment]
![image](https://user-images.githubusercontent.com/28286561/65825567-de18dd80-e2aa-11e9-9d54-6eafb433cc93.png)
拉不起来 我怀疑跟电脑有关系了 中午先更新下系统看看

**Comment by NewFuture** [comment]
这个是 https://github.com/NewFuture/wechat-devtool 的BUG

**Comment by Hansuku** [comment]
ok 看到您的修复方法了 感谢 这边还没推送到 npm 吗

**Comment by NewFuture** [comment]
```
npx wechat-devtool
```
试一下这个能调起开发工具么?

**Comment by Hansuku** [comment]
> ```
> npx wechat-devtool
> ```
> 
> 试一下这个能调起开发工具么?

全局安装 `npm i -g wechat-devtool`，然后在项目外的地方`npx wechat-devtool`可以调起了。
项目内因为 `miniprogram-build` 的依赖还是 `wechat-devtool`的1.2.3 版本 所以无效

**Comment by NewFuture** [comment]
好的，更新一下依赖就行了

**Comment by NewFuture** [comment]
v6.8.1 release 了

**Comment by NewFuture** [comment]
这个问题是开发工具换了包名引起的

mac 试一下这个命令能正常出来么
```bash
defaults read com.tencent.webplusdevtools LastRunAppBundlePath
```

**Comment by Hansuku** [comment]
OK 这边已经正常了 辛苦了👍
