### ISSUE TITLE
start之后能否不强制退出微信开发者工具？

### ISSUE THREAD

**Issue by AnoLu** [NewFuture/miniprogram-build#50]
1. 现在每次start开发者工具都会强制退出。
如果这个行为是#47 issue产生的，现在那个issue close了能否不再强制退出？

2. 能否支持一个feature，就是在VScode这边保存之后，触发微信开发者工具自动编译？

**Comment by NewFuture** [comment]
1. 第一个问题，开着微信开发工具，大量文件替换容易导致微信开发工具文件无法加载的BUG，这个如果后面开发工具支持了可以去掉这个操作。

2. 这个已经有了， start 之后(进入watch mode)保存都会触发自动编译

**Comment by AnoLu** [comment]
OK，非常感谢

**Comment by NewFuture** [comment]
如果想跳过退出可以把start 命令换成
```
"start":"mp build open watch" 
```

**Comment by AnoLu** [comment]
我发现我在VScode保存之后，微信开发者工具并没有自动编译，每次都要编译一下，改动的东西才会显现

**Comment by NewFuture** [comment]
@AnoLu  watch 有输出更新吗？

**Comment by AnoLu** [comment]
> @AnoLu watch 有输出更新吗？

有输出信息，但微信开发工具那边需要手动编译才会更新

**Comment by NewFuture** [comment]
> 有输出信息，但微信开发工具那边需要手动编译才会更新

Windows上的开发工具是自动编译的

**Comment by AnoLu** [comment]
> > 有输出信息，但微信开发工具那边需要手动编译才会更新
> 
> Windows上的开发工具是自动编译的

确实会自动编译。我在笔记本上开发是会自动编译，而在台式上没有自动编译，我看看哪里出问题

**Comment by NewFuture** [comment]
7.0.0 不再退出，使用开发工具的重置文件API更新监听
